import * as mongoose from 'mongoose'

export const IncidentSchema = new mongoose.Schema({
  id: { type: Number, unique: true },
  incidentId: String,
  incidentDescription: String,
  brand: String,
  incidentType: String,
  incidentTypeAttack: String,
  incidentStatus: String,
  source: String,
  country: String,
  countryCode: String,
  url: String,
  elapsedTime: Number,
  inactiveTime: Number,
  incidentDate: String,
  last_checked: String,
  company: Number,
  incidentTakedownStatus: Boolean,
  incidentProactiveDetection: Boolean,
  attachment: Boolean,
  ip: String,
  domain: String,
  html: Boolean,
  whois: String,
  geolocation: Boolean,
  agent: String,
  reactivatedFrom: String,
  relatedIncidents: String,
  incidentLevel: String,
  incidentScore: Number,
  sourceData: Object,
  bookmark: Boolean,
  incidentEvents: [Object]
})
