language: node_js
node_js:
  - '14.15.4'
install:
  - npm install
deploy:
  provider: heroku
  api_key:
    secure: fea5df45-0b0c-48d8-987f-79b6e621ce78
  app: poc-incidents-backend
  on:
    repo: Danachury/poc-incidents_backend
