version: '3.7'
services:
  app:
    container_name: incidents-backend
    build:
      context: ../
      dockerfile: .ops/Dockerfile
    tty: true
    ports:
      - 3000:3000/tcp
    environment:
      PORT: 3000
      PROFILE: dev
      DB_HOST: incidents-backend_database
      DB_PORT: 27017
      DB: gword
      DB_USER: incuser
      DB_PASS: incuser-2021!*
    depends_on:
      - database
    networks:
      - incidents-backend

  database:
    image: mongo
    container_name: incidents-backend_database
    restart: always
    ports:
      - 27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: incuser
      MONGO_INITDB_ROOT_PASSWORD: incuser-2021!*
      MONGO_INITDB_DATABASE: poc
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - incidents-backend

networks:
  incidents-backend:
    driver: bridge
